<!--
var info_url   = "http://www.nps.gov/yell/";
var title      = "Yellowstone Trip";
var cam_img    = "camera_canon_a80.jpg"
var cam_tit    = "Canon Powershot A80, 4.0 Mega Pixels."
var dir        = maindir+"pics/0406yellowstone/";  //directory where pics are
var interval   = 5000;                             //interval for slide show in millisecond
var thumb_dir  = maindir+"thumbnail/";             //thumbnail directory
var ext        = ".jpg";                           //extension of the pic files
var midi_file  = "Kena.mid";
//Seleccion de Bailes Incas
var midi_cr    = new Array("John Kwasnik","http://members.accessbee.com/jkwasnik/midfiles.html");

if(window.usechinese){
    cam_tit    = "佳能Powershot A80, 400万像素。";
    title      = "黄石公园";
}

document.title = title;

function initAlbum(){
    this.length = 2;
    this[0] = new Array();  //store file names
    this[1] = new Array();  //store file infos, shown as browser status
    for (var i=0;i<103;i++){
        this[0][i] = "0406yellowstone__"+(i+1).toString();
        this[1][i] = "";
    }
    if(window.usechinese){
        this[1][0] = "提旦公园";
        this[1][1] = "提旦公园";
        this[1][2] = "提旦公园";
        this[1][3] = "提旦公园游客中心";
        this[1][4] = "提旦公园游客中心";
        this[1][5] = "提旦公园";
        this[1][6] = "提旦公园：珍尼湖";
        this[1][7] = "提旦公园：珍尼湖";
        this[1][8] = "提旦公园：珍尼湖";
        this[1][9] = "提旦公园：摩然峰";
        this[1][10] = "提旦公园：杰克逊湖";
        this[1][11] = "提旦公园：杰克逊湖";
        this[1][12] = "提旦公园：杰克逊湖";
        this[1][13] = "提旦公园：杰克逊湖";
        this[1][14] = "黄石公园：野牛";
        this[1][15] = "黄石公园：野牛漫步车前";
        this[1][16] = "黄石公园：野牛漫山遍野";
        this[1][17] = "黄石公园：熊(照片中心的小黑斑)";
        this[1][18] = "黄石公园：麋(Elk)";
        this[1][19] = "黄石公园：驼鹿(Moose)";
        this[1][20] = "黄石公园：老忠实间歇泉";
        this[1][21] = "黄石公园：老忠实间歇泉";
        this[1][22] = "黄石公园：老忠实间歇泉";
        this[1][23] = "黄石公园：老忠实间歇泉";
        this[1][24] = "黄石公园：老忠实间歇泉";
        this[1][25] = "黄石公园：老忠实间歇泉";
        this[1][26] = "黄石公园：老忠实间歇泉";
        this[1][27] = "黄石公园：老忠实间歇泉";
        this[1][28] = "黄石公园：珍珠间歇泉";
        this[1][29] = "黄石公园：珍珠间歇泉";
        this[1][30] = "黄石公园：美丽塘";
        this[1][31] = "黄石公园：美丽塘";
        this[1][32] = "黄石公园：城堡间歇泉";
        this[1][33] = "黄石公园：多彩塘";
        this[1][34] = "黄石公园：水窖泉";
        this[1][35] = "黄石公园：经常间歇泉";
        this[1][36] = "黄石公园：双子池";
        this[1][37] = "黄石公园：水流里长满了五颜六色的细菌";
        this[1][38] = "黄石公园：沙滩泉";
        this[1][39] = "黄石公园: 祖母绿池";
        this[1][40] = "黄石公园：无畏间歇泉";
        this[1][41] = "黄石公园：巨人间歇泉";
        this[1][42] = "黄石公园：巨人间歇泉";
        this[1][43] = "黄石公园：大间歇泉";
        this[1][44] = "黄石公园：洞穴间歇泉";
        this[1][45] = "黄石公园：洞穴间歇泉";
        this[1][46] = "黄石公园：狮子间歇泉";
        this[1][47] = "黄石公园：水泵间歇泉";
        this[1][48] = "黄石公园：锯木场间歇泉";
        this[1][49] = "黄石公园：痉挛间歇泉";
        this[1][50] = "黄石公园：蒸汽船间歇泉";
        this[1][51] = "黄石公园：蒸汽船间歇泉";
        this[1][52] = "黄石公园：喷发中的缓慢间歇泉";
        this[1][53] = "黄石公园：喷发中的缓慢间歇泉";
        this[1][54] = "黄石公园：喷发后的缓慢间歇泉";
        this[1][55] = "黄石公园：牵牛花池";
        this[1][56] = "黄石公园：牵牛花池";
        this[1][57] = "黄石公园：牵牛花池";
        this[1][58] = "黄石公园：圆顶和女巨人间歇泉";
        this[1][59] = "黄石公园：分钟间歇泉，由于人为破坏，不再每分钟喷发。";
        this[1][60] = "黄石公园：陶瓷盆地";
        this[1][61] = "黄石公园：泥火山";
        this[1][62] = "黄石公园：开普勒阶梯瀑布";
        this[1][63] = "黄石公园：上瀑布";
        this[1][64] = "黄石公园：汤姆叔叔小道";
        this[1][65] = "黄石公园：下瀑布";
        this[1][66] = "黄石公园：下瀑布";
        this[1][67] = "黄石公园：下瀑布";
        this[1][68] = "黄石公园：下瀑布";
        this[1][69] = "黄石公园：下瀑布";
        this[1][70] = "黄石公园：画家点";
        this[1][71] = "黄石公园：画家点";
        this[1][72] = "黄石公园：土堆地阶";
        this[1][73] = "黄石公园：新蓝泉";
        this[1][74] = "黄石公园：金丝雀泉";
        this[1][75] = "黄石公园：金丝雀泉";
        this[1][76] = "黄石公园：金丝雀泉";
        this[1][77] = "黄石公园：Minerva(智慧女神)地阶";
        this[1][78] = "黄石公园：Minerva地阶";
        this[1][79] = "黄石公园：黄石湖";
        this[1][80] = "黄石公园：黄石湖";
        this[1][81] = "黄石公园：化石树";
        this[1][82] = "黄石公园：苏打丘";
        this[1][83] = "黄石公园：峡谷晚霞";
        this[1][84] = "蒙大拿山区，六月里居然下雪！";
        this[1][85] = "蒙大拿山区";
        this[1][86] = "蒙大拿山区";
        this[1][87] = "蒙大拿山区";
        this[1][88] = "蒙大拿山区";
        this[1][89] = "魔鬼塔国家纪念碑，美国第一个国家纪念碑";
        this[1][90] = "魔鬼塔";
        this[1][91] = "魔鬼塔";
        this[1][92] = "魔鬼塔";
        this[1][93] = "魔鬼塔";
        this[1][94] = "魔鬼塔";
        this[1][95] = "魔鬼塔";
        this[1][96] = "魔鬼塔";
        this[1][97] = "总统头像山(拉续摩山),四位总统是华盛顿, 杰佛逊, 西而多.如瑟佛, 和林肯。";
        this[1][98] = "总统头像山";
        this[1][99] = "总统头像山";
        this[1][100] = "总统头像山";
        this[1][101] = "总统头像山";
        this[1][102] = "总统头像山";
    }else{
        this[1][0] = "Grand Teton National Park: panoramic view";
        this[1][1] = "Grand Teton National Park";
        this[1][2] = "Grand Teton National Park: panoramic view";
        this[1][3] = "Grand Teton National Park: tepee in visitor center";
        this[1][4] = "Grand Teton National Park: tepee in visitor center";
        this[1][5] = "Grand Teton National Park";
        this[1][6] = "Grand Teton National Park: Jenny Lake";
        this[1][7] = "Grand Teton National Park: Jenny Lake";
        this[1][8] = "Grand Teton National Park: Jenny Lake";
        this[1][9] = "Grand Teton National Park: Mount Moran";
        this[1][10] = "Grand Teton National Park: Jackson Lake";
        this[1][11] = "Grand Teton National Park: Jackson Lake panoramic view";
        this[1][12] = "Grand Teton National Park: Jackson Lake";
        this[1][13] = "Grand Teton National Park: Jackson Lake panoramic view";
        this[1][14] = "Yellowstone National Park: bison across the road";
        this[1][15] = "Yellowstone National Park: bison in front of the car";
        this[1][16] = "Yellowstone National Park: bisons roaming in the wild";
        this[1][17] = "Yellowstone National Park: bear and cubs(at the center of the photo)";
        this[1][18] = "Yellowstone National Park: elk";
        this[1][19] = "Yellowstone National Park: moose";
        this[1][20] = "Yellowstone National Park: Old Faithful Geyser";
        this[1][21] = "Yellowstone National Park: Old Faithful Geyser";
        this[1][22] = "Yellowstone National Park: Old Faithful Geyser";
        this[1][23] = "Yellowstone National Park: Old Faithful Geyser";
        this[1][24] = "Yellowstone National Park: Old Faithful Geyser";
        this[1][25] = "Yellowstone National Park: Old Faithful Geyser";
        this[1][26] = "Yellowstone National Park: Old Faithful Geyser";
        this[1][27] = "Yellowstone National Park: Old Faithful Geyser";
        this[1][28] = "Yellowstone National Park: Pearl Geyser";
        this[1][29] = "Yellowstone National Park: Pearl Geyser";
        this[1][30] = "Yellowstone National Park: Beauty Pool";
        this[1][31] = "Yellowstone National Park: Beauty Pool";
        this[1][32] = "Yellowstone National Park: Castle Geyser";
        this[1][33] = "Yellowstone National Park: Chromatic Pool";
        this[1][34] = "Yellowstone National Park: Cistern Spring";
        this[1][35] = "Yellowstone National Park: Constant Geyser";
        this[1][36] = "Yellowstone National Park: Doublet Pool";
        this[1][37] = "Yellowstone National Park: stream with colorful bacteria";
        this[1][38] = "Yellowstone National Park: Beach Spring";
        this[1][39] = "Yellowstone National Park: Emerald Spring";
        this[1][40] = "Yellowstone National Park: Fearless Geyser";
        this[1][41] = "Yellowstone National Park: Giant Geyser";
        this[1][42] = "Yellowstone National Park: Giant Geyser";
        this[1][43] = "Yellowstone National Park: Grand Geyser";
        this[1][44] = "Yellowstone National Park: Grotto Geyser";
        this[1][45] = "Yellowstone National Park: Grotto Geyser";
        this[1][46] = "Yellowstone National Park: Lion Geyser";
        this[1][47] = "Yellowstone National Park: Pump Geyser";
        this[1][48] = "Yellowstone National Park: Sawmill Geyser";
        this[1][49] = "Yellowstone National Park: Spasmodic Geyser";
        this[1][50] = "Yellowstone National Park: Steamboat Geyser";
        this[1][51] = "Yellowstone National Park: Steamboat Geyser";
        this[1][52] = "Yellowstone National Park: Tardy Geyser during eruption";
        this[1][53] = "Yellowstone National Park: Tardy Geyser during eruption";
        this[1][54] = "Yellowstone National Park: Tardy Geyser after eruption";
        this[1][55] = "Yellowstone National Park: Morning Glory Pool";
        this[1][56] = "Yellowstone National Park: Morning Glory Pool";
        this[1][57] = "Yellowstone National Park: Morning Glory Pool";
        this[1][58] = "Yellowstone National Park: Vault and Giantess Geyser";
        this[1][59] = "Yellowstone National Park: Minute Geyser(due to sabotage, the geyser no longer erupts every minute)";
        this[1][60] = "Yellowstone National Park: Porcelain Basin panoramic view";
        this[1][61] = "Yellowstone National Park: Mud Volcano";
        this[1][62] = "Yellowstone National Park: Kepler Cascades";
        this[1][63] = "Yellowstone National Park: Upper Fall";
        this[1][64] = "Yellowstone National Park: Uncle Tom's Trail";
        this[1][65] = "Yellowstone National Park: Lower Fall";
        this[1][66] = "Yellowstone National Park: Lower Fall";
        this[1][67] = "Yellowstone National Park: Lower Fall";
        this[1][68] = "Yellowstone National Park: Lower Fall seen from Artist Point";
        this[1][69] = "Yellowstone National Park: Lower Fall seen from Artist Point";
        this[1][70] = "Yellowstone National Park: Artist Point";
        this[1][71] = "Yellowstone National Park: Artist Point panoramic view";
        this[1][72] = "Yellowstone National Park: Mound Terrace";
        this[1][73] = "Yellowstone National Park: New Blue Spring";
        this[1][74] = "Yellowstone National Park: Canary Spring";
        this[1][75] = "Yellowstone National Park: Canary Spring";
        this[1][76] = "Yellowstone National Park: Canary Spring";
        this[1][77] = "Yellowstone National Park: Minerva Terrace";
        this[1][78] = "Yellowstone National Park: Minerva Terrace";
        this[1][79] = "Yellowstone National Park: Yellowstone Lake";
        this[1][80] = "Yellowstone National Park: Yellowstone Lake panoramic view";
        this[1][81] = "Yellowstone National Park: Petrified Tree";
        this[1][82] = "Yellowstone National Park: Soda Butte";
        this[1][83] = "Yellowstone National Park: Canyon dusk";
        this[1][84] = "Montana mountain(Yes, it is snowing in June!)";
        this[1][85] = "Montana mountain";
        this[1][86] = "Montana mountain";
        this[1][87] = "Montana mountain";
        this[1][88] = "Montana mountain";
        this[1][89] = "Devils Tower National Monument(first national monument)";
        this[1][90] = "Devils Tower National Monument";
        this[1][91] = "Devils Tower National Monument";
        this[1][92] = "Devils Tower National Monument";
        this[1][93] = "Devils Tower National Monument";
        this[1][94] = "Devils Tower National Monument";
        this[1][95] = "Devils Tower National Monument";
        this[1][96] = "Devils Tower National Monument";
        this[1][97] = "Mount Rushmore National Memorial(George Washington, Thomas Jefferson, Theodore Roosevelt, and Abraham Lincoln)";
        this[1][98] = "Mount Rushmore National Memorial";
        this[1][99] = "Mount Rushmore National Memorial";
        this[1][100] = "Mount Rushmore National Memorial";
        this[1][101] = "Mount Rushmore National Memorial";
        this[1][102] = "Mount Rushmore National Memorial";
    }
}

//web counter info
var sc_project   = 613905;
var sc_invisible = 1;
var sc_partition = 3;
var sc_security  = "f5cfdd4f";
//-->
